FROM rust:1.88

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p uploads

# Expose port
EXPOSE 8000

# Default command
CMD ["cargo", "run", "--bin", "backend"]
