version: '3.8'

services:
  recipes-app:
    image: joesweb/kitchen-box:latest  # This will pull the multi-architecture image from Docker Hub
    container_name: kitchen-box
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 192.168.17.24
    environment:
      - API_URL=kitchen-box.joes-web.de  # Override this for different deployments
    volumes:
      # Data persistence
      - recipes_uploads:/app/uploads
      - recipes_pgdata:/app/var/lib/postgresql/data
      - recipes_logs:/var/log/postgresql

volumes:
  recipes_uploads:
    driver: local
  recipes_pgdata:
    driver: local
  recipes_logs:
    driver: local

networks:
  br0:
    external: true
