services:
  kitchen-box:
    image: joesweb/kitchen-box:latest
    container_name: kitchen-box
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 192.168.17.24
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    volumes:
      - kitchen_box_uploads:/app/uploads
      - kitchen_box_pgdata:/var/lib/postgresql/data
      - kitchen_box_logs:/var/log/postgresql

volumes:
  kitchen_box_uploads:
  kitchen_box_pgdata:
  kitchen_box_logs:

networks:
  br0:
    external: true
